GET http://localhost:5000/product/search?q=

###

POST  http://localhost:5000/user/signup
Content-Type: application/json

{
    "username": "Nguyen Huu Long",
    "email": "longnh.0601@gmail.com",
    "password": "khongbiet123",
    "gender": "male",
    "phone": "0944308133",
    "dob": "2001-06-30"
}

###
GET http://localhost:5000/user/activate/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5ndXllbiBIdXUgTG9uZyIsImVtYWlsIjoibG9uZ25oLjA2MDFAZ21haWwuY29tIiwicGFzc3dvcmQiOiJraG9uZ2JpZXQxMjMiLCJnZW5kZXIiOiJtYWxlIiwicGhvbmUiOiIwOTQ0MzA4MTMzIiwiZG9iIjoiMjAwMS0wNi0zMFQwMDowMDowMC4wMDBaIiwiaWF0IjoxNjM0NjI2MTU2LCJleHAiOjE2MzQ2Mjk3NTZ9.re5WGscWHIKoRnBtx5PFsm5swddjzmD2b7pPapOSsis
###

POST https://chito-stationery.herokuapp.com/user/signup
Content-Type: application/json

{
    "username": "Nguyen Huu Long",
    "email": "longnh.0601@gmail.com",
    "password": "khongbiet123"
}

###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "deosoma32@gmail.com",
    "password": "khongbiet123"
}

###
GET http://localhost:5000/read-cookies