GET http://localhost:5000/product/search/ook+sticker

###

POST  http://localhost:5000/user/signup
Content-Type: application/json

{
    "username": "Nguyen Huu Long",
    "email": "deosoma32@gmail.com",
    "password": "khongbiet123"
}

###
GET http://localhost:5000/user/activate/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5ndXllbiBIdXUgTG9uZyIsImVtYWlsIjoiZGVvc29tYTMyQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoia2hvbmdiaWV0MTIzIiwiaWF0IjoxNjMyNjYxNzkzLCJleHAiOjE2MzI2NjUzOTN9.JdnVPaeyZMTZDRkngAlW6jdaDw8MMDrUqe60K1foKDE
###

POST https://chito-stationery.herokuapp.com/user/signup
Content-Type: application/json

{
    "username": "Nguyen Huu Long",
    "email": "longnh.0601@gmail.com",
    "password": "khongbiet123"
}

###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "deosoma32@gmail.com",
    "password": "khongbiet123"
}

###
GET http://localhost:5000/read-cookies